services:
  webapp:
    container_name: webapp-multistage
    build: 
      context: ./www/webapp
      dockerfile: .docker/prod-multistage.Dockerfile
    env_file: .env.local
    volumes:
      - ./www/webapp/src:/app/src
      - ./www/webapp/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - web_network_multistage

networks:
  web_network_multistage:
    external: true