import { InformationCircleIcon } from '@heroicons/react/24/outline';
import { JavaScriptIcon } from '@/ui/components/icons';
import { Card } from '@/lib/types';

export const cards: Card[] = [
	{
		title: 'Card 1',
		description: 'This is a test card',
		icon: JavaScriptIcon,
		href: 'example',
		ratio: '2:1',
	},
	{
		title: 'Card 2',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 3',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 4',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 5',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 6',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 7',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 8',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '3:1',
	},
	{
		title: 'Card 9',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:2',
	},
	{
		title: 'Card 10',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 11',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '2:2',
	},
	{
		title: 'Card 12',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 13',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 14',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 15',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 16',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 17',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 18',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 19',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
	{
		title: 'Card 20',
		description: 'This is a test card',
		icon: InformationCircleIcon,
		href: 'example',
		ratio: '1:1',
	},
];
